# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

# Install .NET 8 SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Restore dependencies
- script: dotnet restore
  displayName: 'Restore dependencies'

# Build project
- script: dotnet build --configuration Release
  displayName: 'Build project'

# Run tests
- script: dotnet test --no-build --verbosity normal
  displayName: 'Run tests'

# Publish project
- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish project'

# Create ZIP package
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/SampleWebApp.zip'
    replaceExistingArchive: true

# Debug step (shows files in pipeline agent)
- script: dir $(Build.ArtifactStagingDirectory)
  displayName: 'Check ZIP file'

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'
    appName: 'samplewebapptushar'
    package: '$(Build.ArtifactStagingDirectory)/SampleWebApp.zip'