# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore
  displayName: Restore dependencies

- script: dotnet build --configuration Release
  displayName: Build project

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: Publish project

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/SampleWebApp.zip'
    replaceExistingArchive: true

- script: dir $(Build.ArtifactStagingDirectory)
  displayName: Verify ZIP

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'
    appName: 'samplewebapptushar'
    package: '$(Build.ArtifactStagingDirectory)/SampleWebApp.zip'