trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration Release
  displayName: 'Build project'

- script: dotnet test --no-build --verbosity normal
  displayName: 'Run tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'   # name of your service connection
    appName: 'samplewebapptushar'          # your App Service name
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'